name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12
    strategy:
      matrix:
        platform: ["iOS Simulator,OS=16.2,name=iPhone 14"]
        xcode: ["Xcode_14.2.app"]
    steps:
      - uses: actions/checkout@v3
      - run: PLATFORM="${{ matrix.platform }}" make test
        env:
          DEVELOPER_DIR: /Applications/${{ matrix.xcode }}/Contents/Developer
