name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: ["iOS Simulator,OS=16.1,name=iPhone 14", "macos,OS=13"]
        xcode: ["Xcode_14.1.app"]
    steps:
      - uses: actions/checkout@v3
      - run: xcodebuild test -scheme Schematics-Package -destination platform="${{ matrix.platform }}"
        env:
          DEVELOPER_DIR: /Applications/${{ matrix.xcode }}/Contents/Developer
