name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: ["iOS Simulator,OS=16.2,name=iPhone 14", "macos,OS=13.1"]
    steps:
      - uses: actions/checkout@v3
      - run: xcodebuild test -scheme Schematics-Package -destination platform="${{ matrix.platform }}"
